name: bonacompra
services:
  postgresql:
    image: postgres:17.5
    environment:
      # 👇 Default value, but here for explicitness. Also creates a db with the same name.
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "127.0.0.1:5432:5432"
